/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adarsh Maurya
 */
public class Browse extends javax.swing.JFrame {

    /**
     * Creates new form Browse
     */
    public Browse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnowner = new javax.swing.JButton();
        btnscript = new javax.swing.JButton();
        btntransaction = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("To see Details Press Buttons");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 20, 550, 80);

        btnowner.setText("Owner INFO");
        btnowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnownerActionPerformed(evt);
            }
        });
        getContentPane().add(btnowner);
        btnowner.setBounds(610, 140, 310, 100);

        btnscript.setText("Script INFO");
        btnscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnscriptActionPerformed(evt);
            }
        });
        getContentPane().add(btnscript);
        btnscript.setBounds(610, 260, 310, 90);

        btntransaction.setText("Transaction INFO");
        btntransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransactionActionPerformed(evt);
            }
        });
        getContentPane().add(btntransaction);
        btntransaction.setBounds(610, 370, 310, 100);

        jButton1.setText("Transaction Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 500, 310, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnownerActionPerformed
        new Owner_info().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnownerActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         int i=0;
        while(i<=1){
             establishconnection ob=new establishconnection();
           String sql1="Select * from flag;";
           ob.execute(sql1);
           try{
               String flag="N";
               while(ob.rs.next())
               flag=ob.rs.getString("ch");
               System.out.println(flag);
               if(flag.equalsIgnoreCase("Y")){
                   System.out.println("database present");
               }
           }
           catch(Exception e){
                System.out.println("creating database....");
              createdb obj=new createdb();
              obj.createDB();
           }
           
             i++;
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnscriptActionPerformed
        new Script_info().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnscriptActionPerformed

    private void btntransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransactionActionPerformed
       new Transaction_info().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btntransactionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Transaction_report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Browse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Browse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Browse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Browse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Browse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnowner;
    private javax.swing.JButton btnscript;
    private javax.swing.JButton btntransaction;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
