
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adarsh Maurya
 */
public class Transaction_info extends javax.swing.JFrame {

    /**
     * Creates new form Transaction_info
     */
     DefaultTableModel model;
     establishconnection ob=new establishconnection();
     int editmode=0;
    public Transaction_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtownername = new javax.swing.JTextField();
        txtscriptname = new javax.swing.JTextField();
        txtB_S = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        txtrate = new javax.swing.JTextField();
        txtbrokerage = new javax.swing.JTextField();
        txtexpenses = new javax.swing.JTextField();
        txtfield_3a = new javax.swing.JTextField();
        txtfield_3b = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnconfirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtS_owner = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtS_script = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Owner_Name");

        jLabel2.setText("Script_Name");

        jLabel3.setText("Bought_Sold");

        jLabel4.setText("Quantity");

        jLabel5.setText("Rate");

        jLabel6.setText("Brokerage");

        jLabel7.setText("Expenses");

        jLabel8.setText("Field_3a");

        jLabel9.setText("Field_3b");

        txtB_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB_SActionPerformed(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsave)
                        .addGap(18, 18, 18)
                        .addComponent(btnconfirm))
                    .addComponent(txtownername, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_3b, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_3a, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtexpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbrokerage, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB_S, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtscriptname, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtownername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtscriptname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtB_S, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtrate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtbrokerage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtexpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtfield_3a, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtfield_3b, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnconfirm))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        getContentPane().add(jPanel1);
        jPanel1.setBounds(12, 100, 421, 551);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(53, 31, 59, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction_ID", "Owner_Name", "Script_Name", "Bought_Sold", "Quantity", "Rate", "Brokerage", "Expenses", "field_3a", "Field_3b"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 30, 973, 585);
        getContentPane().add(txtS_owner);
        txtS_owner.setBounds(930, 690, 151, 42);

        jLabel12.setText("By Owner_name");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(930, 650, 151, 41);
        getContentPane().add(txtS_script);
        txtS_script.setBounds(1140, 690, 138, 42);

        jLabel13.setText("By Script_name");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1140, 650, 138, 41);

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch);
        btnsearch.setBounds(1320, 690, 116, 42);

        btadd.setText("Add New");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        getContentPane().add(btadd);
        btadd.setBounds(390, 690, 140, 41);

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit);
        btnedit.setBounds(560, 690, 129, 41);

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(720, 690, 128, 41);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtB_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB_SActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new Browse().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        setdisable();
        String code="select * from transaction;";
           ob.execute(code);
          model =(DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
           String[] s=new String[10];
           try{
               while(ob.rs.next()){
                   s[0]=ob.rs.getString(1);
                   s[1]=ob.rs.getString(2);
                   s[2]=ob.rs.getString(3);
                   s[3]=ob.rs.getString(4);
                   s[4]=ob.rs.getString(5);
                   s[5]=ob.rs.getString(6);
                   s[6]=ob.rs.getString(7);
                   s[7]=ob.rs.getString(8);
                   s[8]=ob.rs.getString(9);
                   s[9]=ob.rs.getString(10);
                   model.addRow(s);
               }
           }
           catch(Exception e){
               System.out.println("error in getting data");
           }
    }//GEN-LAST:event_formWindowActivated

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        setenable();
    }//GEN-LAST:event_btaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
       String o_name= txtownername.getText();
        String s_name=txtscriptname.getText();
        String b_s=txtB_S.getText();
        double qty=Double.parseDouble(txtquantity.getText());
        double r=Double.parseDouble(txtrate.getText());
        double brk=Double.parseDouble(txtbrokerage.getText());
        double expenses=Double.parseDouble(txtexpenses.getText());
        String field_3a=txtfield_3a.getText();
        String field_3b=txtfield_3b.getText();
   
        
        if(o_name.length()==0||s_name.charAt(0)==' '){
            JOptionPane.showMessageDialog(this,"Please Enter correct details");
        }
        else{
               String sql="insert into transaction(Owner_Name,Script_Name,Bought_sold,Quantity,Rate,Brokerage,Expenses,field_3a,field_3b) values('"+o_name+"','"+s_name+"','"+b_s+"',"+qty+","+r+","+brk+","+expenses+",'"+field_3a+"','"+field_3b+"');";
              int flag=ob.update(sql);
        
        if(flag==1){
            JOptionPane.showMessageDialog(null,"added successfully");
            new Transaction_info().setVisible(true);
            this.dispose();
         }
        else if(flag==0)
                JOptionPane.showMessageDialog(null,"addition failed");
           }
         
        
    }//GEN-LAST:event_btnsaveActionPerformed
    int id=-1;
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         this.editmode=0;
         int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        if(row==-1||column==-1){
            JOptionPane.showMessageDialog(this,"Please select a cell in row which u want to delete.");
        }
        else{
            clearfield();
            setenable();
             btnsave.setEnabled(false);
                btnconfirm.setEnabled(true);
            txtownername.setText((String)jTable1.getValueAt(row, 1));
             txtscriptname.setText((String)jTable1.getValueAt(row, 2));
              txtB_S.setText((String)jTable1.getValueAt(row, 3));
              txtquantity.setText((String)jTable1.getValueAt(row, 4));
              txtrate.setText((String)jTable1.getValueAt(row, 5));
              txtbrokerage.setText((String)jTable1.getValueAt(row, 6));
              txtexpenses.setText((String)jTable1.getValueAt(row, 7));
              txtfield_3a.setText((String)jTable1.getValueAt(row, 8));
              txtfield_3b.setText((String)jTable1.getValueAt(row, 9));
              id=Integer.parseInt((String)jTable1.getValueAt(row,0));
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
         if(this.editmode==0){
        if(id!=-1){
            String sql="Delete from transaction where Transaction_ID="+id+";";
             int flag=ob.update(sql);
        
        if(flag==1){
            JOptionPane.showMessageDialog(null,"Deleted successfully");
            new Script_info().setVisible(true);
            this.dispose();
         }
        else if(flag==0)
                JOptionPane.showMessageDialog(null,"Deletion failed");
        btnconfirm.setEnabled(false);
        id=-1;
        }
        }
        else if(editmode==1){
            String o_name= txtownername.getText();
        String s_name=txtscriptname.getText();
        String b_s=txtB_S.getText();
        double qty=Double.parseDouble(txtquantity.getText());
        double r=Double.parseDouble(txtrate.getText());
        double brk = Double.parseDouble(txtbrokerage.getText());
        double expenses= Double.parseDouble(txtexpenses.getText());
        String field_3a = txtfield_3a.getText();
        String field_3b = txtfield_3b.getText();
        
       if(o_name.length()==0||s_name.charAt(0)==' '){
            JOptionPane.showMessageDialog(this,"Please Enter correct details");
        }
        else{
               String sql="Update transaction set Owner_Name='"+o_name+"',Script_Name='"+s_name+"',Bought_sold='"+b_s+"',Quantity="+qty+",Rate="+r+",Brokerage="+brk+",Expenses="+expenses+",field_3a='"+field_3a+"',field_3b='"+field_3b+"' where Transaction_ID="+id+";";
              int flag=ob.update(sql);
        
        if(flag==1){
            JOptionPane.showMessageDialog(null,"Updated successfully");
            new Transaction_info().setVisible(true);
            this.dispose();
         }
        else if(flag==0)
                JOptionPane.showMessageDialog(null,"Updation failed");
           }
        }
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
          this.editmode=1;
        clearfield();
       int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        if(row==-1||column==-1){
            JOptionPane.showMessageDialog(this,"Please select a cell in row which u want to delete.");
        }
        else{
            setenable();
             btnsave.setEnabled(false);
                btnconfirm.setEnabled(true);
             txtownername.setText((String)jTable1.getValueAt(row, 1));
             txtscriptname.setText((String)jTable1.getValueAt(row, 2));
              txtB_S.setText((String)jTable1.getValueAt(row, 3));
              txtquantity.setText((String)jTable1.getValueAt(row, 4));
              txtrate.setText((String)jTable1.getValueAt(row, 5));
              txtbrokerage.setText((String)jTable1.getValueAt(row, 6));
              txtexpenses.setText((String)jTable1.getValueAt(row, 7));
              txtfield_3a.setText((String)jTable1.getValueAt(row, 8));
              txtfield_3b.setText((String)jTable1.getValueAt(row, 9));
              id=Integer.parseInt((String)jTable1.getValueAt(row,0));
              
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String str1=txtS_owner.getText();
        String str2=txtS_script.getText();
        if(str1.length()==0&&str2.length()==0){
            JOptionPane.showMessageDialog(this, "Please provide owner name or script name or both");
        }
        else{
            String code="Select * from transaction";
            if(str1.length()!=0&&str2.length()==0){
                code="Select * from transaction where Owner_Name='"+str1+"';";
            }
            else if(str1.length()==0&&str2.length()!=0){
                code="Select * from transaction where Script_Name='"+str2+"';";
            }
            else{
                code="Select * from transaction where Owner_Name='"+str1+"' AND Script_Name='"+str2+"';";
            }
         
          ob.execute(code);
          model =(DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
           String[] s=new String[10];
           try{
               while(ob.rs.next()){
                   s[0]=ob.rs.getString(1);
                   s[1]=ob.rs.getString(2);
                   s[2]=ob.rs.getString(3);
                   s[3]=ob.rs.getString(4);
                   s[4]=ob.rs.getString(5);
                   s[5]=ob.rs.getString(6);
                   s[6]=ob.rs.getString(7);
                   s[7]=ob.rs.getString(8);
                   s[8]=ob.rs.getString(9);
                   s[9]=ob.rs.getString(10);
                   model.addRow(s);
               }
           }
           catch(Exception e){
               System.out.println("error in getting data");
           }
           
        }
    }//GEN-LAST:event_btnsearchActionPerformed
    void setdisable(){
        btnsave.setEnabled(false);
        txtB_S.setEnabled(false);
        txtownername.setEnabled(false);
        txtscriptname.setEnabled(false);
        txtquantity.setEnabled(false);
        txtrate.setEnabled(false);
        txtbrokerage.setEnabled(false);
        txtexpenses.setEnabled(false);
        txtfield_3a.setEnabled(false);
        txtfield_3b.setEnabled(false);
        btnconfirm.setEnabled(false); 
    }
    void setenable(){
         btnsave.setEnabled(true);
        txtB_S.setEnabled(true);
        txtownername.setEnabled(true);
        txtscriptname.setEnabled(true);
        txtquantity.setEnabled(true);
        txtrate.setEnabled(true);
        txtbrokerage.setEnabled(true);
        txtexpenses.setEnabled(true);
        txtfield_3a.setEnabled(true);
        txtfield_3b.setEnabled(true);
        txtownername.setEnabled(true); 
    }
    void clearfield(){
          txtB_S.setText("");
        txtownername.setText("");
        txtscriptname.setText("");
        txtquantity.setText("");
        txtrate.setText("");
        txtbrokerage.setText("");
        txtexpenses.setText("");
        txtfield_3a.setText("");
        txtfield_3b.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtB_S;
    private javax.swing.JTextField txtS_owner;
    private javax.swing.JTextField txtS_script;
    private javax.swing.JTextField txtbrokerage;
    private javax.swing.JTextField txtexpenses;
    private javax.swing.JTextField txtfield_3a;
    private javax.swing.JTextField txtfield_3b;
    private javax.swing.JTextField txtownername;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtrate;
    private javax.swing.JTextField txtscriptname;
    // End of variables declaration//GEN-END:variables
}
